import type { Post, Block } from './types';

export const POSTS_STANDALONE_1: Post[] = [
  {
    slug: 'i-raised-9-5m-and-couldnt-read-my-own-codebase',
    title: 'I Raised $9.5M and Still Couldn\'t Read My Own Codebase. Then AI Happened.',
    subtitle: 'Then AI happened. Here\'s what changed when the wall between founders and engineering finally came down.',
    excerpt: 'TINYpulse raised $9.5M with top investors. The founder still couldn\'t read the codebase. Here\'s what changed when AI collapsed the wall between founders and engineering.',
    date: 'Apr 2, 2026',
    readTime: '5 min read',
    category: 'AI Leadership',
    tags: ['founders learning developer tools with AI', 'non-technical founder developer stack', 'GitHub Terminal Vercel Supabase for founders', 'Claude AI coding for non-technical founders', 'founder technical skills 2026', '50/50 era', 'TINYpulse'],
    image: '/blog/images/i-raised-9-5m.webp',
  },
  {
    slug: 'the-cms-is-dead-ai-killed-it',
    title: 'The CMS Is Dead. AI Killed It.',
    subtitle: 'Non-technical founders can now control their content and ship like engineers. No WordPress. No plugins. No waiting on developers.',
    excerpt: 'AI replaced the CMS. Here is the 4-step system non-technical founders use to control their content and ship like engineers. No code required.',
    date: 'Apr 1, 2026',
    readTime: '5 min read',
    category: 'Claude Code',
    tags: ['CMS', 'AI infrastructure', 'content management', 'markdown', 'static sites', 'non-technical founders', 'Claude', 'GitHub', 'Vercel'],
    image: '/blog/images/the-cms-is-dead.webp',
  },
  {
    slug: 'using-ai-was-2025-leading-ai-is-2026',
    title: 'Using AI Was 2025. Leading AI Is 2026.',
    subtitle: 'The 50/50 Era is here. Teams now manage 50% people, 50% AI. Leaders who lead AI--not just use it--will define the next generation.',
    excerpt: 'The 50/50 Era is here: teams now manage 50% people, 50% AI. Leaders who lead AI--not just use it--will define the next generation of leadership.',
    date: 'Mar 30, 2026',
    readTime: '5 min read',
    category: 'AI Leadership',
    tags: ['50/50 era', 'AI leadership', 'Jack Dorsey', 'Block layoffs', 'SaaS disruption', 'workforce transformation', 'AI co-worker'],
    image: '/blog/images/using-ai-vs-leading-ai.webp',
  },
  {
    slug: 'your-team-needs-this-skill',
    title: 'Your Team Needs This Skill',
    subtitle: 'Leadership used to be 100% people. That changed. The other 50% is AI. And most leaders have no idea how to lead it.',
    excerpt: 'Leadership used to be 100% people. Now half of your team is AI. Two skills unlock the other 50%: ABC (Always Be Cataloguing) and AI workflow design for business.',
    date: 'Apr 3, 2026',
    readTime: '5 min read',
    category: 'AI Leadership',
    tags: ['leading AI teams', 'AI workflow design', 'always be cataloguing', 'executive AI leadership', '50/50 era', 'AI orchestration', 'AI skills gap 2026'],
    image: '/blog/images/your-team-needs-this-skill.webp',
  },
  {
    slug: 'how-to-set-fast-goals-that-dont-fade',
    title: 'FAST Goals: How to Build a Goal System That Doesn\'t Fade',
    subtitle: 'Most teams don\'t fail because they set the wrong goals. They fail because the goals disappear by week three.',
    excerpt: 'FAST goals keep OKRs alive. Frequently discussed, Ambitious, Specific, Transparent: the MIT Sloan framework that makes team goals drive behavior past week three.',
    date: 'Apr 7, 2026',
    readTime: '6 min read',
    category: 'AI Leadership',
    tags: ['FAST goals', 'FAST goal framework', 'OKRs and FAST', 'goal setting framework', 'MIT Sloan FAST goals', 'how to make OKRs stick', 'leadership goal setting', 'operating rhythm', 'AI for goal tracking'],
    image: '/blog/images/fast-goals-mit.webp',
  },
  {
    slug: 'four-offices-of-the-future',
    title: 'The Four Offices of the Future: Why Your Org Chart Is the Reason AI Isn\'t Working',
    subtitle: '95% of companies see no ROI from AI. Not because the technology doesn\'t work. Organizations can\'t connect it to outcomes. Here\'s why.',
    excerpt: '95% of companies see no ROI from AI. Not because the technology doesn\'t work. The Four Offices framework diagnoses where AI should create value and why it currently isn\'t.',
    date: 'Mar 19, 2026',
    readTime: '8 min read',
    category: 'AI Leadership',
    tags: ['Four Offices framework', 'AI ROI', 'organizational design', 'AI leadership', 'Revenue Talent Operations Innovation', 'workflow documentation', 'AI strategy'],
    image: '/blog/images/four-offices-of-the-future.webp',
  },
  {
    slug: 'hotel-ai-personalization-guest-experience',
    title: 'The Hotel AI Personalization Gap',
    subtitle: 'Hotels have more guest data than ever. They just don\'t know how to activate it.',
    excerpt: 'Hotels collect guest data but fail to activate it. The AI Personalization Flywheel explains how hotel AI personalization creates real competitive advantage through data-driven experiences.',
    date: 'Mar 30, 2026',
    readTime: '4 min read',
    category: 'AI Leadership',
    tags: ['hotel AI personalization', 'guest experience', 'AI Personalization Flywheel', 'hospitality AI', 'data activation', 'personalization paradox'],
    image: '/blog/images/hotel-ai-personalization.webp',
  },
];

export const BLOCKS_STANDALONE_1: Record<string, Block[]> = {
  /* ───────────────────────────────────────────────
   * 1. I Raised $9.5M and Couldn't Read My Own Codebase
   * ─────────────────────────────────────────────── */
  'i-raised-9-5m-and-couldnt-read-my-own-codebase': [
    { tag: 'tl-dr', items: [
      'Raising $9.5M and hiring great engineers doesn\'t mean a founder understands the stack. That wall was normal -- until AI made it inefficient.',
      'The gap was never about skill. It was about having a guide. <a href="https://claude.ai" target="_blank" rel="noopener">Claude</a> is that guide.',
      'Days, not weeks: GitHub, Terminal, Vercel, and <a href="https://supabase.com" target="_blank" rel="noopener">Supabase</a> are now accessible to any non-technical founder willing to engage.',
      'The real payoff isn\'t shipping features yourself. It\'s the mental models you develop -- and the clarity that compounds across your whole team.',
    ]},
    { tag: 'pull-quote', text: 'At <a href="https://www.tinypulse.com" target="_blank" rel="noopener">TINYpulse</a> we raised $9.5 million. We had <a href="https://www.baselinevc.com" target="_blank" rel="noopener">Baseline Venture Capital</a> behind us. Michael Dearing and Mark Roberge on the board, Doug Bergum among our investors. A real team. Real product. Real traction. And I could not tell you the difference between a repository and a folder.' },
    { tag: 'p', text: 'That wasn\'t laziness. That was just how it worked. The founder set direction, hired smart people, and trusted them to handle the technical execution. The engineering work lived on the other side of a wall, and the wall felt normal.' },
    { tag: 'p', text: 'It was normal. Until AI made it inefficient.' },
    { tag: 'h2', text: 'The Wall Was Never About Skill' },
    { tag: 'p', text: 'Here\'s what I understand now that I didn\'t then: the gap between a founder and the developer stack was never really a skill gap. It was a guide gap.' },
    { tag: 'p', text: 'GitHub existed. Terminal existed. Vercel existed. Supabase existed. Every tutorial, every documentation page, every YouTube walkthrough existed too. The tools were always there.' },
    { tag: 'pull-quote', text: 'What was missing was someone who could sit next to you, understand what you were trying to build, and walk you through every command, every error, every connection point in real time. Without judgment. Without impatience. Without billing you by the hour.' },
    { tag: 'p', text: 'That person didn\'t exist before. Now it does. It\'s Claude.' },
    { tag: 'h2', text: 'What I Actually Learned, and How Fast' },
    { tag: 'p', text: 'I want to be specific about the timeline because I think it will surprise you.' },
    { tag: 'stat-callout', stats: [
      { value: 'Days.', label: 'Not weeks. Not a bootcamp. Days.' },
    ]},
    { tag: 'p', text: 'Within a few days of actually engaging with this stack, I was pushing code from my computer to GitHub, deploying it live on Vercel, and connecting it to a Supabase database. Something that would have required a developer, a sprint, and a Slack thread now took an afternoon.' },
    { tag: 'p', text: 'The moment it clicked was when I replaced the CMS systems running several of my sites. Tools I had been paying hundreds of dollars a month for, each with their own logins, their own interfaces, their own friction. I replaced them by building directly in the stack and managing everything from my Claude account. Cleaner, faster, and the cost collapsed. <a href="/blog/the-cms-is-dead-ai-killed-it">I wrote the full story here.</a>' },
    { tag: 'emphasis-box', text: 'That is not a small thing. That is a <strong>structural change in what a founder can do alone.</strong>' },
    { tag: 'h2', text: 'The Four Tools and What They Actually Are' },
    { tag: 'p', text: 'If you\'ve been avoiding this stack, here\'s what it actually is. Not what it sounds like. What it is.' },
    { tag: 'h2', text: 'What Actually Changes When You Go Inside the Stack' },
    { tag: 'p', text: 'This is the part nobody is writing about.' },
    { tag: 'p', text: 'Everyone is talking about founders learning to code. That\'s not the story. The story is what happens to your thinking when you\'re no longer receiving the technical work through a filter.' },
    { tag: 'p', text: 'When I started moving through this stack myself, I didn\'t just get faster at building things. I started developing mental models my team didn\'t have yet. The CMS insight above is one of them. I could see what was changing and why, faster than anyone waiting for a briefing.' },
    { tag: 'pull-quote', text: 'Those mental models become direction. Direction becomes velocity. And here is the real payoff: you can turn your team into a technical army.' },
    { tag: 'p', text: 'Not because they all learn to code. Because the person at the top is finally speaking the language -- setting the direction clearly, challenging assumptions early, and multiplying that capacity across every person below them. When the founder understands the stack, the whole organization moves differently.' },
    { tag: 'emphasis-box', text: 'That\'s what changed for me. Not that I can ship a feature myself. It\'s that I can <strong>provide clarity faster than I ever could before</strong>, and that clarity compounds.' },
    { tag: 'h2', text: 'The Opportunity Cost Is Real and It\'s Right Now' },
    { tag: 'p', text: 'We are in the 50/50 era. Half of every workflow is becoming AI. The founders who understand both halves -- the human work and the AI work -- will build things that others simply can\'t see yet.' },
    { tag: 'p', text: 'The developer stack used to be the wall between a founder\'s vision and its execution. Claude took that wall down. What used to take months of gradual exposure now takes days of focused engagement with the right guide in the room.' },
    { tag: 'p', text: 'The founders who go inside the stack will develop mental models that others won\'t have. They\'ll ship faster. They\'ll lead more clearly. They\'ll ask better questions and make better calls. The gap between them and the founders still standing outside the wall is opening right now.' },
    { tag: 'p', text: 'If you believe what I believe -- that the non-technical founder is dead, that we should be leading the other 50% rather than outsourcing it -- then GitHub, Terminal, Vercel, and Supabase are not optional tools to eventually get around to.' },
    { tag: 'p', text: 'They\'re the new baseline. Start with one. Let Claude walk you through the rest.' },
    { tag: 'conclusion-box', title: 'Ready to Go Inside the Stack?', paragraphs: [
      'The AI Officer Institute teaches founders and executives how to build and lead AI-native systems from scratch. Not theory. The actual stack. The actual workflows. The same ones running this website right now.',
      '<strong>The wall is down for anyone willing to walk through it.</strong> <a href="/certification">Learn more about the AI Officer certification program</a> and join the operators building on what actually works. Once you understand the Four Offices of the Future -- Revenue, Talent, Operations, Innovation -- you\'ll see exactly where your stack should go to work: read <a href="/blog/four-offices-of-the-future">The Four Offices of the Future</a> to connect this to business outcomes.',
      'Join the <a href="/community">Leadership in the AI Era</a> community to share what you\'re building and learn from founders who are already inside the stack.',
    ]},
    { tag: 'faq', question: 'Can a non-technical founder really learn GitHub and Terminal?', answer: 'Yes -- and faster than you\'d expect. The barrier was never a skill gap. It was a guide gap. Every tool existed before AI arrived. What was missing was someone who could walk you through every command, every error, every connection point in real time without judgment or a billing clock. That guide now exists. It\'s Claude.' },
    { tag: 'faq', question: 'What is the developer stack founders should learn first?', answer: 'Start with four tools: GitHub (where code lives and moves), Terminal (direct, fast, no friction), Vercel (write, push, live -- immediately), and Supabase (your database layer, connected cleanly into the rest of the stack). Claude walks you through all of it. Days, not weeks.' },
    { tag: 'faq', question: 'What changes when a founder goes inside the developer stack?', answer: 'You stop receiving technical work through a filter. You start developing mental models your team doesn\'t have yet -- seeing what\'s changing and why before anyone waits for a briefing. That clarity compounds. You don\'t need to ship features yourself. You need to provide direction faster than you ever could before.' },
    { tag: 'faq', question: 'What is the 50/50 era?', answer: 'Half of every workflow is becoming AI. The founders who understand both halves -- the human work and the AI work -- will build things that others simply can\'t see yet. The 50/50 era is the transition point where AI literacy is no longer optional for anyone at the top of an organization.' },
  ],

  /* ───────────────────────────────────────────────
   * 2. The CMS Is Dead. AI Killed It.
   * ─────────────────────────────────────────────── */
  'the-cms-is-dead-ai-killed-it': [
    { tag: 'tl-dr', items: [
      'Every CMS makes the same tradeoff: ease of use or design freedom. AI eliminates that tradeoff entirely.',
      'AI is not a better CMS. It is the replacement. Content in markdown files, pages built on demand, deployed via GitHub and Vercel.',
      'The 4-step system: markdown files, AI-generated pages, GitHub push, Vercel deploy. Setup takes an afternoon.',
      'Non-technical founders can now operate like engineers. The barrier was never technical. It was assumption.',
    ]},
    { tag: 'pull-quote', text: 'My first business after leaving Microsoft was a CMS for nightclubs and restaurants. The problem was simple: owners needed to update their sites constantly but were paying developers a fortune to change an event listing. So I built a system to let them do it themselves. It worked. But every CMS since has fought the same war. Ease of use versus design freedom. AI just ended that war.' },
    { tag: 'h2', text: 'The Problem' },
    { tag: 'p', text: 'WordPress, Squarespace, Wix, <a href="https://webflow.com" target="_blank" rel="noopener">Webflow</a>. They all started simple, then bloated into massive platforms trying to balance two things that fight each other: ease of use and design freedom.' },
    { tag: 'p', text: 'Then Medium came along and said, "We are just going to take design freedom away. You will probably mess it up anyway." And they were not entirely wrong.' },
    { tag: 'p', text: 'Framer lets you build beautiful sites fast. But at the end of the day, it is still a CMS. Still controlling what you can do through predefined templates, components, and content models.' },
    { tag: 'pull-quote', text: 'Want five different blog layouts? Your CMS needs five templates. Want different designs for a how-to guide versus a thesis post versus a listicle? Your CMS just got exorbitantly big.' },
    { tag: 'p', text: 'Every CMS makes the same tradeoff. AI eliminates the tradeoff entirely.' },
    { tag: 'h2', text: 'The Solution' },
    { tag: 'p', text: 'AI is not a better CMS. It is the replacement.' },
    { tag: 'emphasis-box', text: '<strong>The shift is fundamental.</strong> A CMS stores your content in a database and renders it through a rigid template system. With AI, none of that matters. The AI stays in the same chat window. Generate the content, go into your web project, say: move this into the blog. It knows to update the index. It knows whether the post is featured. It handles the SEO, the GEO optimization, the image placement. All of it.' },
    { tag: 'p', text: 'I can pick a style. I can point it to images organized in a specific folder. I can create any layout I want for any post, every single time. Full control without ever needing an engineer.' },
    { tag: 'h2', text: 'How It Works' },
    { tag: 'p', text: 'The 4-step system that replaced my CMS. Built using Claude\'s Cowork feature, organized projects, and three tools any non-technical founder can set up in an afternoon.' },
    { tag: 'ol-item', text: '<strong>Content in Markdown</strong> -- Content lives as <code>.md</code> files in organized folders. Not in a database. The file system is the database. Portable, version-controlled, readable by any tool. Always be cataloging. That is the new ABC.' },
    { tag: 'ol-item', text: '<strong>AI Generates Pages</strong> -- A separate project handles the website. AI translates content into pages. React, HTML, whatever architecture you want. Static pages load faster, full stop. No weird dynamic URLs. No SEO redirect chains.' },
    { tag: 'ol-item', text: '<strong>Push to GitHub</strong> -- GitHub used to be reserved for engineers. Not anymore. Claude generates the terminal commands. You copy, paste, and run. Operate like a power engineer without knowing Git internals.' },
    { tag: 'ol-item', text: '<strong>Deploy with Vercel</strong> -- Vercel connects to your GitHub repository and deploys automatically on every push. Setup takes minutes. Claude walks you through the entire configuration. A production website that deploys on every commit, zero DevOps knowledge required.' },
    { tag: 'h2', text: 'A Note on Databases' },
    { tag: 'p', text: 'Am I saying databases are dead? Hell no. I am a database guy at the core. But they do not need to be overused the way CMS platforms have been using them.' },
    { tag: 'p', text: 'Transactional data. User accounts. Analytics. Not blog posts. A file system with well-organized markdown is simpler, more portable, and more AI-friendly for content workflows. Your AI can read, write, and organize markdown files natively. It cannot do the same with a WordPress database.' },
    { tag: 'p', text: 'Databases are not going away. They are just being overused. The right tool for the right job.' },
    { tag: 'h2', text: 'What Changes' },
    { tag: 'p', text: 'If you have ever been frustrated by your website, this is the unlock.' },
    { tag: 'p', text: 'You do not need to learn to code. You do not need to hire a developer for every content change. You do not need to wrestle with a CMS that was built for a different era. The tools are here right now: Claude, GitHub, Vercel, organized folders. That is the entire stack.' },
    { tag: 'p', text: 'The barrier was never technical. It was the assumption that you needed someone technical to do this for you. That assumption is now wrong. Semi-technical or non-technical founders can control their content and ship like engineers. Today. Not next year. Not when the tools get better. Right now.' },
    { tag: 'emphasis-box', text: '<strong>The real shift:</strong> When AI is the CMS, you are not limited to what a platform allows. You are limited only by what you can describe. And describing things, it turns out, is something founders are very good at.' },
    { tag: 'conclusion-box', title: 'Ready to Build Without a CMS?', paragraphs: [
      'The AI Officer Institute teaches founders and executives how to build and operate AI-native systems from scratch. Not theory. The actual stack. The actual workflows. The same ones running this website right now.',
      '<strong>The CMS era is over for anyone willing to move.</strong> <a href="/certification">Learn more about the AI Officer certification program</a> and join the operators building on what actually works. The organizational lens for where this shift belongs in your business is in <a href="/blog/four-offices-of-the-future">The Four Offices of the Future</a> -- the Operations office is exactly where your CMS replacement lives.',
      'Our weekly <a href="/coaching">AI Coaching</a> sessions are where founders walk through live builds like this one and get structured support from Dave. Join the <a href="/community">Leadership in the AI Era</a> community to share what you\'re building.',
    ]},
    { tag: 'faq', question: 'Can AI really replace a CMS?', answer: 'Yes. AI doesn\'t improve the CMS model. It replaces it. A CMS stores content in a database and renders it through rigid templates. With an AI-driven workflow, content lives as portable markdown files, the AI generates any page layout on demand, and static HTML is pushed directly to GitHub and deployed via Vercel. No database. No plugins. No templates. Full control.' },
    { tag: 'faq', question: 'What is the 4-step system for publishing without a CMS?', answer: 'Step 1: Store content as .md files in organized folders -- the file system is your database. Step 2: Use AI to generate pages in React, HTML, or whatever architecture you want. Step 3: Push to GitHub using terminal commands Claude generates for you. Step 4: Deploy automatically with Vercel, which connects to your GitHub repo and deploys on every push.' },
    { tag: 'faq', question: 'Do you need to know how to code to use this workflow?', answer: 'No. Claude generates the terminal commands. You copy, paste, and run them. You get a production website that deploys on every commit with zero DevOps knowledge required. The real barrier was never technical. It was the assumption that you needed someone technical to do this for you.' },
    { tag: 'faq', question: 'What tools do you need for the AI content workflow?', answer: 'The full stack is Claude, GitHub, Vercel, and organized folders with markdown files. That is it. Setup takes an afternoon. Total cost is a fraction of any enterprise CMS, and you have more design freedom than any template system can offer.' },
  ],

  /* ───────────────────────────────────────────────
   * 3. Using AI Was 2025. Leading AI Is 2026.
   * ─────────────────────────────────────────────── */
  'using-ai-was-2025-leading-ai-is-2026': [
    { tag: 'tl-dr', items: [
      'Jack Dorsey cut 40% of <a href="https://block.xyz" target="_blank" rel="noopener">Block\'s workforce</a>. Stock jumped 24%. Block is already profitable -- this wasn\'t survival.',
      'Using AI in 2025 was about experimentation. Leading AI in 2026 is about managing AI as a co-worker.',
      'The 50/50 Era: your team is now 50% people, 50% AI systems. Leadership skills must evolve accordingly.',
      'The companies moving now are building the operational advantage that will be nearly impossible to close later.',
    ]},
    { tag: 'pull-quote', text: 'Block was profitable. Growing. Gross profit hit $2.87 billion last quarter, up 26% year over year. Jack Dorsey didn\'t cut 40% of his workforce because the business was failing. He did it because he believes AI has fundamentally changed what it takes to run a company. And the market listened: stock up 24% in after-hours trading.' },
    { tag: 'h2', text: 'The Signal Nobody\'s Talking About' },
    { tag: 'p', text: 'While every other CEO trims 5-10% and calls it "restructuring," Dorsey went 40% in a single move. And here\'s the part that should keep you up at night: he said most companies are late, and he expects the majority to reach the same conclusion within the next year.' },
    { tag: 'stat-callout', stats: [
      { value: '40%', label: 'Workforce cut in one move' },
      { value: '+24%', label: 'Stock surge after announcement' },
      { value: '$2.87B', label: 'Q4 gross profit, up 26% YoY' },
    ]},
    { tag: 'p', text: 'This wasn\'t a cost-cutting exercise. It was a statement about the future. Block didn\'t need to cut costs. It needed to restructure for a new operating model where AI is a co-worker, not a tool.' },
    { tag: 'h2', text: 'SaaS Is Getting Disrupted from the Bottom Up' },
    { tag: 'p', text: 'The media framed this as "AI replacing workers." That\'s only half the story. The bigger disruption is happening underneath.' },
    { tag: 'p', text: 'I built my own CRM. Right now I\'m building a recruiting system. It\'ll take 3-4 weeks. Packaged AI scanning resumes. AI recording and rating interviews. Automated workflows. All running on a database that costs $50/month.' },
    { tag: 'p', text: 'I don\'t need the ATS anymore. I don\'t need the CRM anymore. Startups everywhere are doing the same thing. When companies can build their own tools in weeks instead of buying six-figure SaaS contracts, the math changes fast. Pricing pressure. Margin compression. Headcount cuts.' },
    { tag: 'p', text: 'Bloomberg analyst Dan Ives called it a "trillion-dollar tech wipeout." This isn\'t a blip. The market is pricing in a structural shift. We covered the full breakdown of Dorsey\'s decision in <a href="/blog/jack-dorsey-layoffs">Jack Dorsey Layoffs: What 4,000 Cuts Reveal About AI and SaaS</a>.' },
    { tag: 'h2', text: 'The Research Says: One Clean Cut' },
    { tag: 'p', text: 'My partner Dr. Brooks Holtom at <a href="https://www.georgetown.edu" target="_blank" rel="noopener">Georgetown University</a> was quoted in <a href="https://www.businessinsider.com" target="_blank" rel="noopener">Business Insider</a> on the Block layoffs. His research on employee retention and organizational shocks is some of the most cited in the field.' },
    { tag: 'p', text: 'The research is clear: repeated rounds of layoffs create what Holtom calls "layoff fatigue and chronic anxiety." People stop working and start wondering if they\'re next. Morale drops. Productivity drops. Trust drops.' },
    { tag: 'pull-quote', text: 'One clean cut beats the slow bleed. Every time.' },
    { tag: 'p', text: '<strong>Georgetown Research Finding:</strong> 40% is extreme. Holtom acknowledged that. But Dorsey paired it with 20 weeks of severance plus tenure bonuses, six months of healthcare, equity vesting through May, and corporate devices employees could keep. Holtom told Business Insider the overall approach aligned with what good management research recommends.' },
    { tag: 'h2', text: 'Welcome to the 50/50 Era' },
    { tag: 'p', text: 'Here\'s what is actually happening. We\'re entering an era where your team isn\'t just humans anymore. Half your workforce will be people. Half will be AI. Not in some distant future. Now.' },
    { tag: 'p', text: 'When Dorsey said a "significantly smaller team, using the tools we\'re building, can do more and do it better," he wasn\'t describing a cost-cutting exercise. He was describing a new operating model. One where AI isn\'t a tool you hand to employees. It\'s a co-worker on the team that you need to manage, direct, and integrate into how your company actually works.' },
    { tag: 'emphasis-box', text: '<strong>Last year, the conversation was about using AI.</strong> Experimenting. Trying ChatGPT. Running a pilot. That was fine for 2025. In 2026, the leaders who win will be the ones who figure out how to bring AI onto their team as a co-worker and actually lead it.' },
    { tag: 'p', text: 'Who reports to the AI system? Who trains it? Who\'s accountable when it makes a bad call? Who decides what it should and shouldn\'t do? These aren\'t technical questions. They\'re leadership questions. The <a href="/blog/four-offices-of-the-future">Four Offices framework</a> is a practical starting point for that diagnostic.' },
    { tag: 'h2', text: 'What This Means for You' },
    { tag: 'p', text: 'Dorsey put it simply: "I\'d rather get there honestly and on our own terms than be forced into it reactively." The question isn\'t whether this is coming to your company. It\'s whether you\'ll be ready when it does.' },
    { tag: 'p', text: 'Look at your org chart. How many roles could AI do alongside a smaller, sharper human team? Not "someday." This quarter. The companies moving now are building the operational advantage that will be nearly impossible to close later.' },
    { tag: 'p', text: 'The CEO who figures this out first has the advantage. The one who waits gets Dorsey\'d: a reactive, painful restructuring forced by competitive pressure instead of strategic choice. That\'s the alternative to leading this transition yourself.' },
    { tag: 'p', text: '"I know how to use AI" is table stakes now. The valuable skill is leading a team where half the contributors aren\'t human. That\'s the skill gap nobody\'s talking about yet. The people who close it first will define the next generation of leadership.' },
    { tag: 'conclusion-box', title: 'Ready to Lead in the 50/50 Era?', paragraphs: [
      'The AI Officer Institute teaches founders and executives how to lead teams where AI is a co-worker, not just a tool. Master the frameworks, the conversations, and the organizational structures that turn AI from a capability into a competitive advantage.',
      '<strong>The 50/50 Era is here. The companies moving now are building the structures that will define the next decade.</strong> <a href="/certification">Learn more about our certification program</a> and join the leaders reshaping AI-driven organizations in the <a href="/community">Leadership in the AI Era</a> community.',
      'Bring your specific challenges to a weekly <a href="/coaching">AI Coaching</a> session -- where executives get coached in real time on the AI problems they\'re actually facing.',
    ]},
    { tag: 'faq', question: 'Why did Block\'s stock go up 24% after Dorsey cut 40% of the workforce?', answer: 'Block was already profitable -- gross profit hit $2.87B last quarter, up 26% YoY. The market\'s reaction wasn\'t about cost-cutting. It was about a new operating model where a significantly smaller team, using AI, can do more and do it better. Investors are pricing in structural efficiency, not just headcount reduction.' },
    { tag: 'faq', question: 'What is the 50/50 era of leadership?', answer: 'The 50/50 era means your team isn\'t just humans anymore. Half your effective workforce will be people. Half will be AI systems. This changes the entire job of leadership -- from managing only humans to managing both humans and AI as co-workers on the same team.' },
    { tag: 'faq', question: 'What is the difference between using AI and leading AI?', answer: 'Using AI means experimenting with tools -- trying ChatGPT, running pilots, adopting software. That was 2025. Leading AI means bringing AI onto your team as a co-worker: deciding who reports to the AI system, who trains it, who is accountable when it makes a bad call, and what it should and shouldn\'t do. These are leadership questions, not technical ones.' },
    { tag: 'faq', question: 'What should founders do about the AI and workforce shift right now?', answer: 'Look at your org chart and ask how many roles could AI do alongside a smaller, sharper human team -- not someday, but this quarter. The companies moving now are building the operational advantage that will be nearly impossible to close later. Dorsey\'s framing: better to get there honestly on your own terms than be forced into it reactively.' },
  ],

  /* ───────────────────────────────────────────────
   * 4. Your Team Needs This Skill
   * ─────────────────────────────────────────────── */
  'your-team-needs-this-skill': [
    { tag: 'tl-dr', items: [
      'We are in the 50/50 era -- half of every workflow is becoming AI. Most leaders were trained only to lead people.',
      'Skill #1: ABC -- Always Be Cataloguing. Your AI is only as good as what you give it. Get your catalog in order first.',
      'Skill #2: Workflow Design -- the ability to map how work flows through a system of humans and AI agents.',
      'The proof: caiocoach.com went from idea to live site in 4.5 hours, while running two businesses simultaneously.',
    ]},
    { tag: 'pull-quote', text: 'My coaching session with Eric and Julien ended at 12:30pm on a Thursday. By 4pm, I messaged Julien: the site is up. The coaching session is live. In between, I had three other meetings, payroll, and a lesson to prepare for. I was not sitting at a keyboard. I was running two businesses. My AI team was building.' },
    { tag: 'h2', text: 'The Job Got Bigger' },
    { tag: 'p', text: 'Leadership used to be one thing: lead people.' },
    { tag: 'p', text: 'You hired well. You built culture. You ran good meetings. You held people accountable. That was the job. A hundred percent of it.' },
    { tag: 'p', text: 'That has changed.' },
    { tag: 'pull-quote', text: 'We are in the 50/50 era. Half of every workflow is becoming AI. Half of the work your team does can now be directed to, delegated to, and executed by AI agents, tools, and systems.' },
    { tag: 'p', text: 'That is not a prediction. It is happening now, in real companies, in real time. We wrote about the early signals of this shift in <a href="/blog/using-ai-was-2025-leading-ai-is-2026">Using AI Was 2025. Leading AI Is 2026.</a> -- but the skill gap has only widened since.' },
    { tag: 'p', text: 'But here is the problem. Most leaders only learned to lead people. Nobody taught them how to lead AI. Nobody taught them how to build a team where half the contributors do not have a pulse. And because of that, most organizations investing heavily in AI are getting almost nothing back.' },
    { tag: 'emphasis-box', text: 'Not because the tools don\'t work. Because <strong>nobody in the room knows how to lead them.</strong> The job got bigger. The skill set has not caught up.' },
    { tag: 'h2', text: 'Two Skills. No One Is Teaching Them.' },
    { tag: 'p', text: 'If you want to lead AI -- not just use it -- you need two capabilities. Neither of them is a technology skill. Both of them are leadership disciplines.' },
    { tag: 'p', text: 'Build both of these and you are not just more productive. You are building a compounding advantage that is very hard for anyone behind you to close.' },
    { tag: 'h2', text: 'ABC: Always Be Cataloguing' },
    { tag: 'p', text: 'Your AI is only as good as what you give it. If your files are scattered, your images unnamed, your brand voice locked inside your own head, your AI team is working blind. It will hallucinate. It will be generic. It will produce work that feels off, because it has nothing real to work from.' },
    { tag: 'p', text: 'I preach this constantly. Catalog everything. Name your files with intention. Build style guides. Document your voice, your process, your standards.' },
    { tag: 'p', text: 'And then I looked at my own image library.' },
    { tag: 'pull-quote', text: 'No naming conventions. No structure. Files I could not find. I was telling other founders to catalog, and I had not done it myself.' },
    { tag: 'p', text: 'That is the gap. Most leaders have knowledge they cannot transfer. Insight that lives only in their head. Systems that fall apart when they step away. If your AI cannot find it, it does not exist.' },
    { tag: 'p', text: 'ABC is the precondition for everything else. Before you build a workflow, before you delegate a task, before you run an agent, you need to have your catalog in order. That means your brand assets, your tone of voice, your process documentation, your templates, your frameworks.' },
    { tag: 'emphasis-box', text: 'This is not optional. <strong>It is how you onboard your AI team.</strong> Skip it, and you are building on sand.' },
    { tag: 'h2', text: 'Workflow Design Is the New Org Chart' },
    { tag: 'p', text: 'The second skill is orchestration. Not prompting. Not experimenting with tools. Orchestration is the ability to design AI workflows for business outcomes -- mapping how work flows through a system that includes both humans and AI.' },
    { tag: 'p', text: 'Think about it the same way you think about your org chart. Who does what? In what order? What triggers the next step? Who is accountable for the output? When does a human need to be in the loop?' },
    { tag: 'p', text: 'Those questions used to only apply to people. Now they apply to <a href="/certification">AI agents</a> too. This is the capability we build in the <a href="https://www.ai-officer.com/certification" target="_blank" rel="noopener">AI Officer certification</a> -- specifically in the Agentic AI track.' },
    { tag: 'p', text: 'When I built <a href="https://www.caiocoach.com" target="_blank" rel="noopener">caiocoach.com</a>, I was not running one conversation with one AI. I was running parallel threads inside a single project, each with clear instructions, each drawing from the same style guides and context files. One thread handled the site structure. One handled the content. One handled the coaching program pages. The site was pushed to <a href="https://github.com" target="_blank" rel="noopener">GitHub</a> and deployed live via <a href="https://vercel.com" target="_blank" rel="noopener">Vercel</a> automatically. I directed the work. My AI team executed it.' },
    { tag: 'p', text: 'That is workflow design. It is the skill of knowing how to break a goal into components, assign each component to the right resource, and coordinate the output into something coherent.' },
    { tag: 'emphasis-box', text: 'Founders who learn this do not just get faster. <strong>They get to a different category of output entirely.</strong>' },
    { tag: 'h2', text: '4.5 Hours' },
    { tag: 'p', text: 'Here is what the caiocoach.com build actually looked like.' },
    { tag: 'p', text: 'Coaching session ends at 12:30. I have a full afternoon. Three meetings. Payroll. A lesson to prep. The domain has been sitting unused for a year.' },
    { tag: 'stat-callout', stats: [
      { value: '4.5 hrs', label: 'Domain to live site' },
    ]},
    { tag: 'p', text: 'That result was not possible without ABC. I had my style guides ready. My brand voice documented. My process for building AIO content already structured and tested. My AI team had what it needed to work.' },
    { tag: 'p', text: 'And it was not possible without workflow design. I did not hand one AI a vague request and hope. I mapped the build, ran parallel threads, and directed the output.' },
    { tag: 'p', text: 'The creative generalist with these two skills is not 10% more productive. The leverage is a different order of magnitude entirely.' },
    { tag: 'h2', text: 'The Question Is Not Whether to Lead AI' },
    { tag: 'p', text: 'The question is whether you will figure it out before your competitors do.' },
    { tag: 'p', text: 'Eric and Julien asked the right questions in that coaching session. They were already thinking like AI leaders. They just did not have the framework yet.' },
    { tag: 'p', text: 'ABC and workflow design are not tools. They are not software. They are leadership capabilities. And right now, they are rare.' },
    { tag: 'p', text: 'The founders who build these skills first are not just more productive. They are building a compounding advantage that is very hard for anyone behind them to close. Your AI team is already waiting. The question is whether you know how to lead it.' },
    { tag: 'conclusion-box', title: 'Ready to Lead AI?', paragraphs: [
      'The AI Officer Institute exists to build the leadership capabilities the 50/50 era demands. If you want to move from AI user to AI leader -- and see what ABC and workflow design look like inside a real operating system -- earn your <a href="/certification">AI Officer Certification</a> or join a weekly <a href="/coaching">AI Coaching</a> session.',
      'Connect with executives who are already navigating this transition in the <a href="/community">Leadership in the AI Era</a> community -- leaders from 30+ countries sharing what\'s working.',
    ]},
    { tag: 'faq', question: 'What skills do leaders need to manage AI teams?', answer: 'Two foundational skills: ABC (Always Be Cataloguing) -- the discipline of organizing your assets, brand voice, and process documentation so AI can actually use them -- and workflow design, the ability to map how work flows through a system that includes both humans and AI agents.' },
    { tag: 'faq', question: 'How do you lead an AI workflow?', answer: 'The same way you think about an org chart. Who does what? In what order? What triggers the next step? Who is accountable for the output? When does a human need to be in the loop? Workflow design means breaking a goal into components, assigning each to the right resource -- human or AI -- and coordinating the output into something coherent.' },
    { tag: 'faq', question: 'What is the difference between using AI and leading AI?', answer: 'Using AI means prompting a single tool to complete a single task. Leading AI means orchestrating multiple AI agents within structured workflows, feeding them the right context, and directing their combined output toward a business outcome -- the same way a leader directs a team of people.' },
    { tag: 'faq', question: 'Why is most AI investment returning nothing?', answer: 'Not because the tools don\'t work. Because nobody in the room knows how to lead them. Leaders were trained to lead people. Nobody trained them to lead AI agents, build systems where half the contributors don\'t have a pulse, or design workflows that combine human judgment with machine execution.' },
  ],

  /* ───────────────────────────────────────────────
   * 5. How to Set FAST Goals That Don't Fade
   * ─────────────────────────────────────────────── */
  'how-to-set-fast-goals-that-dont-fade': [
    { tag: 'tl-dr', items: [
      'Goals don\'t fail because they\'re wrong. They fail because they stop showing up in conversation after the planning meeting.',
      'OKRs give you structure: a clear objective and measurable key results that tell you whether you actually moved.',
      'Cascade goals from organization to teams to individuals so everyone can see how their work connects to the same priorities.',
      'FAST keeps the system alive: Frequently discussed, Ambitious, Specific, Transparent.',
      'AI handles the tracking layer at scale, so the leader stops being the system and starts using the system.',
    ]},
    { tag: 'pull-quote', text: 'If you\'ve sat through a quarterly planning session, you know how this goes. The team gets in a room. You set goals. Someone writes them down in a slide or a Notion page. Everyone leaves feeling aligned. Then work starts. A client escalates. A deadline moves. The urgent takes over. And four weeks later, those goals are sitting in a doc that nobody opens.' },
    { tag: 'p', text: 'They haven\'t disappeared. They\'ve just stopped mattering.' },
    { tag: 'p', text: 'That\'s not a motivation problem. It\'s a systems problem. And there\'s a way to fix it. This post walks through two frameworks, OKRs and FAST, and how to use them together to build a goal system that actually drives behavior across your organization.' },
    { tag: 'h2', text: 'Start With the Objective' },
    { tag: 'p', text: 'An objective is the direction. It\'s what you\'re trying to achieve.' },
    { tag: 'p', text: 'It\'s not a task. It\'s not a number. It\'s a clear statement of where you want to go, simple enough that people can remember it and strong enough that it creates focus. A good objective answers one question: what are we trying to accomplish?' },
    { tag: 'p', text: 'Instead of "run more campaigns," the objective is "become the market leader in customer experience." Instead of "improve the team," it\'s "build a culture where top performers stay." The difference is direction. The objective sets the destination. Everything else tells you whether you\'re getting there.' },
    { tag: 'pull-quote', text: 'Keep it short. Keep it memorable. If someone can\'t repeat it back to you two weeks later, it\'s too long.' },
    { tag: 'h2', text: 'Define the Key Results' },
    { tag: 'p', text: 'Key results are how you know if you\'re making progress. This is where things become measurable. Key results describe outcomes, not activities. They tell you whether something actually changed.' },
    { tag: 'p', text: 'If the objective is to become the market leader in customer experience, a key result might be increasing customer satisfaction from 72 to 85, or reducing churn from 8% to 4% over the quarter. Those are outcomes. You can look at them and know whether you moved.' },
    { tag: 'p', text: 'The trap most teams fall into is treating tasks as key results. "Launch a new campaign" is not a key result. "Hire three people" is not a key result. Those are actions. Key results measure the impact of those actions.' },
    { tag: 'emphasis-box', text: 'The test is simple: does this number tell you whether you actually got better at the thing that matters? <strong>If yes, it\'s a key result. If it just tells you that you did something, it\'s a task.</strong>' },
    { tag: 'p', text: 'When you put objectives and key results together, strategy stops being abstract. You define what success looks like. You track whether you\'re getting there.' },
    { tag: 'h2', text: 'Cascade From Organization to Teams' },
    { tag: 'p', text: 'Once the organizational priorities are clear, the next step is translating them into what each team actually does. This is where OKRs create real alignment, and where alignment usually starts to break.' },
    { tag: 'p', text: 'At the organizational level, leaders set direction. The priorities are clear. Then those priorities move to teams, and interpretation begins. Marketing hears one thing. Product hears another. By the time it reaches individuals, people are working hard but not always in the same direction.' },
    { tag: 'p', text: 'The fix is cascading. Each team looks at the organizational objective and asks one question: what do we need to deliver for this to happen?' },
    { tag: 'p', text: 'Marketing might focus on acquisition. Product might focus on engagement. Sales might focus on retention or expansion. Each team contributes differently, but all of those contributions connect back to the same organizational objective. This is where alignment becomes real. It\'s no longer just a statement at the top. It\'s reflected in what each function is responsible for.' },
    { tag: 'h2', text: 'Connect Goals to Individuals' },
    { tag: 'p', text: 'At the individual level, OKRs answer a very practical question: what is my role in all of this?' },
    { tag: 'p', text: 'This is the step that creates ownership. Instead of working through a task list, each person understands the outcome they are responsible for. They can look at their goals and see how their work connects to the team and to the organization.' },
    { tag: 'p', text: 'It also creates autonomy. When someone understands the outcome they\'re accountable for, they have freedom to decide how to get there. You don\'t have to manage every step. You manage the result.' },
    { tag: 'p', text: 'When this works, alignment doesn\'t feel forced. It feels natural, because every level of the organization is connected to the same set of priorities.' },
    { tag: 'emphasis-box', text: 'Take a moment with this. Set one organizational objective. Write two key results. Then try to cascade it. <strong>If that exercise feels messy, you\'ve found the gap. That\'s exactly where the work is.</strong>' },
    { tag: 'h2', text: 'Layer In FAST' },
    { tag: 'p', text: 'OKRs give you structure. FAST keeps that structure alive.' },
    { tag: 'p', text: 'FAST comes from research at MIT Sloan and stands for Frequently discussed, Ambitious, Specific, and Transparent. The insight behind it is straightforward: goals that live on paper don\'t change behavior. Goals that show up in conversation do.' },
    { tag: 'p', text: 'People focus on what gets talked about. If goals only come up once a quarter, they won\'t drive much. If they show up every week in one-on-ones and team meetings, they start shaping decisions, priorities, and effort.' },
    { tag: 'h2', text: 'Use OKRs and FAST Together' },
    { tag: 'p', text: 'OKRs and FAST solve two different problems. Put them together and you get something most organizations don\'t have: clarity and consistency at the same time.' },
    { tag: 'p', text: 'Without FAST, OKRs become something you set and revisit at the end of the quarter, right before you set the next ones. The goals exist, but they don\'t drive behavior. They\'re a planning artifact, not an operating rhythm.' },
    { tag: 'p', text: 'Without OKRs, conversations don\'t have a clear target. You can have great check-ins and still drift, because nobody is sure what success looks like.' },
    { tag: 'p', text: 'When the two work together, you define what success looks like and you talk about it constantly. Goals become part of how the organization operates, not just how it plans.' },
    { tag: 'h2', text: 'Use AI to Keep the System Running' },
    { tag: 'p', text: 'As organizations grow, maintaining this rhythm gets harder. More people, more goals, more conversations to track. Most leaders end up managing by memory, which means things fall through.' },
    { tag: 'p', text: 'This is where AI becomes genuinely useful, not as a decision-maker, but as a support system.' },
    { tag: 'p', text: 'AI can track progress across multiple goals without relying on memory. It can prepare performance conversations by summarizing what happened since the last check-in. It can surface patterns across a team that are hard to see when you\'re managing ten people at once.' },
    { tag: 'p', text: 'Think about what takes the most time in running a good goal system. It\'s not setting the goals. It\'s staying connected to them: knowing where things stand, who needs support, what\'s blocking progress. AI handles that tracking so leaders can focus on the conversation itself.' },
    { tag: 'pull-quote', text: 'The leader stops being the system. The leader uses the system.' },
    { tag: 'h2', text: 'Build the System, Not Just the Goals' },
    { tag: 'p', text: 'Most organizations have goals. Few have a system that keeps goals alive.' },
    { tag: 'p', text: 'The seven steps here are not complicated. Set a clear objective. Define measurable outcomes. Cascade them through the organization. Connect them to individuals. Keep them in conversation. Use AI to maintain the rhythm as you scale.' },
    { tag: 'p', text: 'The discipline is not in setting the goals. It\'s in building the rhythm that makes them impossible to ignore. That\'s what allows an organization to move from intention to execution, consistently, quarter after quarter.' },
    { tag: 'conclusion-box', title: 'Build Your Operating System', paragraphs: [
      'The AI Officer Institute exists to build the leadership capabilities the AI era demands. If you want to learn how to install this kind of operating system inside your organization, earn your <a href="/certification">AI Officer Certification</a> or join a weekly <a href="/coaching">AI Coaching</a> session.',
      'Connect with executives who are already navigating this transition in the <a href="/community">Leadership in the AI Era</a> community, with leaders from 30+ countries sharing what\'s working.',
    ]},
    { tag: 'faq', question: 'Why do most goals fail by week three?', answer: 'Not because they were the wrong goals. Because nobody talks about them after the planning meeting. Urgent work takes over, the goals stop showing up in conversation, and four weeks later they\'re sitting in a doc nobody opens. It\'s a systems problem, not a motivation problem.' },
    { tag: 'faq', question: 'What\'s the difference between an objective and a key result?', answer: 'An objective is the direction: a clear, memorable statement of what you\'re trying to achieve. A key result is the measurable outcome that tells you whether you got there. "Become the market leader in customer experience" is an objective. "Increase customer satisfaction from 72 to 85" is a key result. Tasks like "launch a campaign" or "hire three people" are neither.' },
    { tag: 'faq', question: 'How do OKRs and FAST work together?', answer: 'OKRs answer "what are we trying to achieve?" FAST answers "how do we make sure we don\'t forget about it?" OKRs give you the structure. FAST (Frequently discussed, Ambitious, Specific, Transparent) keeps that structure alive in everyday conversations. Without FAST, OKRs become a planning artifact. Without OKRs, conversations have no clear target.' },
    { tag: 'faq', question: 'How can AI help maintain a goal system?', answer: 'AI handles the tracking layer that usually breaks down at scale. It can monitor progress across dozens of goals without relying on memory, prep performance conversations by summarizing what happened since the last check-in, and surface team-wide patterns that are hard to see when you\'re managing ten people at once. The leader stops being the system and starts using the system.' },
  ],

  /* ───────────────────────────────────────────────
   * 6. Four Offices of the Future
   * ─────────────────────────────────────────────── */
  'four-offices-of-the-future': [
    { tag: 'h2', text: 'The Reality Check' },
    { tag: 'p', text: '95% of companies see no ROI from AI. Not because the technology doesn\'t work. Because organizations can\'t connect AI to outcomes.' },
    { tag: 'p', text: 'I know this because I keep testing it. Last week, 102 founders in Australia. Same exercise I\'ve run with over 500 founders across multiple countries. I ask them: where should AI be making you money or saving you money right now? They always have answers. Then I ask why it isn\'t. And every time, the same three things come up.' },
    { tag: 'p', text: 'The data is scattered. The workflows aren\'t documented. Nobody owns it.' },
    { tag: 'p', text: 'Every company. Same three answers. These aren\'t technology problems. They\'re leadership problems.' },
    { tag: 'h2', text: 'The Job Changed and We Didn\'t' },
    { tag: 'p', text: 'Chamath Palihapitiya made this point recently on the All In podcast. His company is at the forefront of AI, investing millions, and they\'re still not seeing doubled or tripled revenue. Meanwhile, Jack Dorsey just laid off 40% of Block. 70% of those were engineers. The company is profitable.' },
    { tag: 'p', text: 'The companies getting ROI aren\'t the ones spending the most on AI. They\'re the ones who restructured how they think about their business.' },
    { tag: 'p', text: 'Leadership used to be 100% about people. Now it\'s 50% people and 50% artificial intelligence. And most of us have only been practicing one half.' },
    { tag: 'p', text: 'The second half requires a completely different skill set. Organizing data. Documenting workflows. Cataloguing every process and decision point in your business. Without people trained to lead this work, the tools just sit there.' },
    { tag: 'h2', text: 'Every Outcome Falls Into Four Buckets' },
    { tag: 'p', text: 'Every outcome your business cares about maps to one of four offices.' },
    { tag: 'p', text: '<strong>Revenue</strong> -- Everything related to your customer that drives new sales and retention. But it only works when someone owns the whole pipeline. Not just marketing. Not just sales. The whole thing. When it\'s siloed, AI optimizes pieces that don\'t connect.' },
    { tag: 'p', text: '<strong>Talent</strong> -- The full lifecycle of your people. Hiring, onboarding, development, culture. Treat your people processes as a product, not a process. See how to build this end-to-end in <a href="/blog/talent-system-that-scales">How to Build a Talent System That Actually Scales</a>.' },
    { tag: 'p', text: '<strong>Operations</strong> -- Everything that keeps the business running. But it only works when you redesign workflows, not patch them. If you automate chaos, you get faster chaos.' },
    { tag: 'p', text: '<strong>Innovation</strong> -- The lens on the future of your business. But it only works when you give teams space to think and tools to build. Innovation doesn\'t die from lack of ideas. It dies from lack of bandwidth.' },
    { tag: 'p', text: 'This isn\'t a new org chart. It\'s a diagnostic. A way to look at your business and ask: where should AI be creating value, and why isn\'t it?' },
    { tag: 'h2', text: 'What Founders Actually Prioritize' },
    { tag: 'p', text: 'When the Australian room picked their most important office, the split was revealing.' },
    { tag: 'stat-callout', stats: [
      { value: '50%', label: 'Revenue' },
      { value: '30%', label: 'Operations' },
      { value: '5%', label: 'Talent' },
    ]},
    { tag: 'p', text: 'Revenue makes sense. That\'s where founders feel the most pressure. Operations is where the waste is most visible.' },
    { tag: 'callout', label: 'Run This Diagnostic', text: 'For each of the four offices, where should AI be making you money or saving you money right now? Why isn\'t it happening? What\'s the gap between intention and reality? Which office would unlock the most value if it worked perfectly? Who owns the end-to-end workflow in that office?' },
    { tag: 'p', text: 'Talent at 5% is the office everyone underestimates. One founder discovered during the exercise that their entire onboarding process lived in one person\'s head. If that person left, the process left with them. Another realized the same person "owned" AI across all four offices, which meant nobody really owned anything.' },
    { tag: 'p', text: 'The companies that figure out Talent first will have a structural advantage over everyone else. Because the constraint isn\'t the technology. It\'s having people who know how to lead AI programs and engineers who can build them. That\'s the hire most founders haven\'t made yet.' },
    { tag: 'h2', text: 'The Documentation Is the Build Spec' },
    { tag: 'p', text: 'Here\'s what most people miss about getting from idea to prototype. The hard work isn\'t the coding. It\'s the documentation.' },
    { tag: 'p', text: 'Every workflow follows the same pattern: <strong>Trigger, Data, Classify, Route, Respond, Action, Log.</strong> Basic workflows are predetermined and exact. A smart workflow adds a decision layer where AI classifies inputs, routes them down different paths, and responds appropriately. That\'s where guardrails matter.' },
    { tag: 'p', text: 'In Australia, the founders documented one workflow each using this pattern. Then they paired up and pressure-tested each other\'s work with one question: could a new hire follow this? Because if a new hire can follow it, AI can follow it.' },
    { tag: 'p', text: 'Then something interesting happened. The documented workflow became the prompt. They pasted it into an AI tool and vibe coded interactive prototypes in under an hour. Proposal generators. <a href="/blog/interactive-ai-avatars">Onboarding avatar tools</a>. Customer feedback routers. All built from workflows that didn\'t exist that morning. The documentation wasn\'t prep work for the build. The documentation was the build spec.' },
    { tag: 'h2', text: 'The Path to ROI' },
    { tag: 'p', text: 'The gap between the 95% and the 5% isn\'t tools, talent, or budget. It\'s the organizational work underneath. The cataloguing. The documenting. The designing of workflows before anyone writes a line of code.' },
    { tag: 'p', text: 'That work requires two things most companies don\'t have yet: people trained to lead AI programs who understand both the business and the technology, and engineers who can turn documented workflows into production systems.' },
    { tag: 'p', text: 'The founders who invest in those roles now will have a compounding advantage. The ones who wait will keep spending on AI tools that sit unused.' },
    { tag: 'p', text: '<strong>The path to ROI was never the technology. It was always the leadership\'s ability to connect AI to the outcomes that matter.</strong>' },
    { tag: 'conclusion-box', title: 'Ready to get structured on AI?', paragraphs: [
      'The Four Offices Framework is the diagnostic tool that connects your org chart to outcomes. The <a href="/certification">AI Officer Certification</a> teaches you how to apply this framework across your business and build the systems that actually create ROI.',
      'If you want to work through the diagnostic with your specific business, our weekly <a href="/coaching">AI Coaching</a> sessions are where executives bring their real challenges and get coached in real time.',
      'Join the <a href="/community">Leadership in the AI Era</a> community to connect with other executives applying this framework across industries and geographies.',
    ]},
    { tag: 'faq', question: 'Why do 95% of companies see no ROI from AI?', answer: 'It\'s not because the technology doesn\'t work. Organizations can\'t connect AI to measurable business outcomes because of three leadership problems: scattered data, undocumented workflows, and unclear ownership. These are structural issues that require organizational redesign, not better software.' },
    { tag: 'faq', question: 'What are the Four Offices and why do they matter?', answer: 'The Four Offices are Revenue, Talent, Operations, and Innovation. Every outcome your business cares about maps to one of these. They form a diagnostic framework to identify where AI can create the most value and why it currently isn\'t. Each office requires different approaches and ownership structures to work effectively with AI.' },
    { tag: 'faq', question: 'Which office should we prioritize first?', answer: 'Most founders prioritize Revenue (50%), followed by Operations (30%). However, Talent is often the most underestimated at only 5% priority. The companies that figure out Talent first by developing documentation and processes gain a structural advantage. There\'s no universally correct answer, it depends on your current constraints and what will unlock the most value in your business.' },
    { tag: 'faq', question: 'What\'s the documentation workflow pattern?', answer: 'The pattern is: Trigger, Data, Classify, Route, Respond, Action, Log. This template helps you document any workflow in a way that both humans and AI can follow. The key insight is that if a new hire can follow your documented workflow, AI can follow it. This documentation becomes your AI prompt and build specification.' },
    { tag: 'faq', question: 'What two things do we need to achieve real ROI from AI?', answer: 'First, people trained to lead AI programs who understand both business strategy and technology. Second, engineers who can turn documented workflows into production systems. These roles create a compounding advantage for organizations that invest early. Without both, you\'ll continue to spend on AI tools that remain underutilized.' },
  ],

  /* ───────────────────────────────────────────────
   * 7. Hotel AI Personalization: The Guest Experience Gap
   * ─────────────────────────────────────────────── */
  'hotel-ai-personalization-guest-experience': [
    { tag: 'pull-quote', text: 'I am sitting in a <a href="https://www.marriott.com" target="_blank" rel="noopener">Marriott</a> hotel room on my birthday weekend. Surrounded by paper. Folded brochures, printed menus, a welcome letter with my name typed at the top. On the desk: a welcome amenity basket. Juice I won\'t drink. Crackers I don\'t want. Some strange fruit I can\'t identify. What I actually want is information about tennis courts and water sports. A list of restaurants serving Korean or Vietnamese food without onions. A quiet workspace with decent coffee. None of that is anywhere.' },
    { tag: 'callout', label: 'The Core Problem', text: 'Hotels have more guest data than ever before. They just don\'t know how to activate it. Most collect the basics: names, birthdays, room preferences. They don\'t connect those signals to anything that changes the actual experience. The basket on my desk is proof. Someone spent real money on it. And none of it is something I would ever want.' },
    { tag: 'h2', text: 'The Personalization Paradox' },
    { tag: 'p', text: 'Hotels want to create personalized experiences. To do that, they need data. But guests only share data when they already feel understood.' },
    { tag: 'p', text: 'It\'s a loop with no entry point.' },
    { tag: 'p', text: 'When guests see no value in sharing, they stop sharing. The result is generic service every time, for every guest.' },
    { tag: 'h2', text: 'What Hotel AI Personalization Actually Looks Like' },
    { tag: 'p', text: 'Here is what a good hotel AI personalization system looks like in practice.' },
    { tag: 'p', text: 'It starts before you arrive. You book a room. An <a href="/blog/interactive-ai-avatars">AI-assisted avatar concierge</a> reaches out in your preferred language, available 24 hours a day. It already knows you don\'t eat onions. It suggests the crab pasta from the newest menu. It asks if you\'d like to book a tennis coach and recommends available times.' },
    { tag: 'p', text: 'When you arrive, check-in takes two minutes. The front desk wishes you a happy birthday. The system asks if you\'d like to book a massage at a nearby spa after your tennis session -- because it knows those are things you value.' },
    { tag: 'p', text: 'This is not science fiction. My clients are building this right now. The tools exist. The data is there. The gap is not the AI itself.' },
    { tag: 'p', text: 'The gap is how data gets collected, connected, and activated.' },
    { tag: 'h2', text: 'The AI Personalization Flywheel' },
    { tag: 'p', text: 'The hospitality brands getting this right are not doing it with better technology. They are doing it with a better approach to data.' },
    { tag: 'p', text: 'I call it the <strong>AI Personalization Flywheel</strong>. Here is how it works:' },
    { tag: 'emphasis-box', text: '<strong>1. Capture signals</strong> from every guest interaction. <strong>2. Extract patterns</strong> using AI to find meaningful preferences. <strong>3. Drive experiences</strong> that feel personalized. <strong>4. Build trust</strong> so guests willingly share more. <strong>5. Improve personalization</strong> with better data. Each cycle makes the system stronger.' },
    { tag: 'p', text: 'Unlike a one-time data project, this flywheel builds with every cycle. Hotels running this model have seen revenue growth up to 30% as guests respond to experiences built around their actual preferences -- not assumptions.' },
    { tag: 'pull-quote', text: 'Half of every workflow in hospitality is becoming AI. The brands winning are not the ones with the most data. They are the ones who know how to lead people and AI as a team to activate that data.' },
    { tag: 'h2', text: 'The Real Problem Is Leadership, Not Technology' },
    { tag: 'p', text: '95% of organizations investing in AI are getting zero return. Hospitality is no different.' },
    { tag: 'p', text: 'The technology works. The data exists. What is missing is someone in the room who knows how to lead an AI personalization program -- someone who can bridge the gap between guest data sitting in a CRM and the experience that actually lands in room 412.' },
    { tag: 'p', text: 'That is the capability hotels need to build. Not more expensive amenities. Not fancier lobbies. Leaders who understand how to run people and AI together.' },
    { tag: 'h2', text: 'Key Takeaways' },
    { tag: 'p', text: '<strong>Data Without Activation Is Wasted</strong> -- Hotels collect guest data constantly but fail to use it in real time. The gap isn\'t data collection -- it\'s the systems and leadership to activate that data into memorable experiences.' },
    { tag: 'p', text: '<strong>Personalization Builds Trust, Trust Builds Data</strong> -- When guests feel understood, they share more willingly. This creates a flywheel where each cycle of personalization makes the next one stronger, driving measurable revenue impact.' },
    { tag: 'p', text: '<strong>The Competitive Advantage Is Leadership</strong> -- The barrier to hotel AI personalization isn\'t the technology. It\'s having leaders who understand how to connect data infrastructure with people management to deliver experiences at scale.' },
    { tag: 'conclusion-box', title: 'Ready to Build Hotel AI That Works?', paragraphs: [
      'The AI Personalization Flywheel isn\'t just strategy -- it\'s a system. The <a href="/certification">AI Officer Certification</a> teaches you how to implement this exact framework in hospitality and other service-driven businesses. You\'ll learn how to connect guest data, structure your leadership team, and create experiences that drive revenue growth.',
      'The organizational structure that makes personalization possible at scale maps directly to <a href="/blog/four-offices-of-the-future">The Four Offices of the Future</a> -- particularly the Revenue and Operations offices. That\'s the diagnostic framework for connecting AI to business outcomes.',
      'Join the <a href="/community">Leadership in the AI Era</a> community to connect with hospitality leaders and executives from 30+ countries who are implementing these systems right now.',
    ]},
    { tag: 'faq', question: 'What is hotel AI personalization?', answer: 'Hotel AI personalization uses guest data and AI to tailor experiences to individual preferences -- from dining and room settings to activity recommendations and timing. The goal is to move from generic service to experiences that feel designed for each specific guest.' },
    { tag: 'faq', question: 'Why do most hotels fail at personalization despite having data?', answer: 'Most hotels collect guest data but don\'t connect it across systems or activate it in real time. The bottleneck is not data volume. It is how data gets organized, interpreted, and used to drive decisions at the property level.' },
    { tag: 'faq', question: 'What is the AI Personalization Flywheel?', answer: 'The AI Personalization Flywheel is a cycle where guest signals feed AI insights, which drive personalized experiences, which build trust, which leads guests to share more data, which improves the next interaction. Each cycle makes the system stronger -- unlike a one-time data project.' },
    { tag: 'faq', question: 'How much revenue impact can hotel AI personalization deliver?', answer: 'Hotels implementing AI-driven personalization programs have seen revenue growth of up to 30%, driven by higher guest satisfaction and increased spend per stay.' },
    { tag: 'faq', question: 'What do hotels actually need to get started?', answer: 'The first step is connecting guest data across systems: booking, loyalty, food and beverage, spa, and activities. From there, AI can begin identifying patterns and driving personalized touchpoints. The larger requirement is having leaders who understand how to run an AI program at scale -- not just use the tools, but lead the people and the systems together.' },
  ],
};
